<a href="https://colab.research.google.com/github/Praharsh04/Praharsh04/blob/main/Learning_Pytorch_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

Fri Aug 22 18:21:57 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   65C    P8             11W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

## 00. Pytorch Fundamental

In [203]:
import torch
import numpy as nnp
import pandas as pd
import matplotlib as plt
print(torch.__version__)

2.8.0+cu126


## Introduction to Tensors


1.  Creating Tensors
      Oytircg tensors are created using torch.Tensor()




In [204]:
# Scaler
scaler  = torch.tensor(7)
scaler

tensor(7)

In [205]:
scaler.ndim

0

In [206]:
scaler.item()

7

In [207]:
# Vector
vector = torch.tensor([7,7])
vector.ndim

1

In [208]:
vector.shape

torch.Size([2])

In [209]:
# MATRIX

MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [210]:
MATRIX.ndim

2

In [211]:
MATRIX.shape

torch.Size([2, 2])

In [212]:
# TENSOR
TENSOR  = torch.tensor([[[1,2,3],
                         [8,9,1],
                         [4,7,0]]])

In [213]:
TENSOR

tensor([[[1, 2, 3],
         [8, 9, 1],
         [4, 7, 0]]])

In [214]:
TENSOR.ndim

3

In [215]:
TENSOR.shape

torch.Size([1, 3, 3])

## Random Tensors
#####CMD + MM for markdawn

#### the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random number`

In [216]:
# Create a random tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7778, 0.7501, 0.8881, 0.7542],
        [0.9306, 0.9721, 0.6776, 0.9185],
        [0.1071, 0.8082, 0.0076, 0.8508]])

In [217]:
random_tensor.ndim

2

In [218]:
random_tensor.shape

torch.Size([3, 4])

In [219]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

In [220]:
 # Create a tensor with all zeroes

zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [221]:
# Create a tensor with all ones

ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [222]:
ones.dtype

torch.float32

In [223]:
ones.ndim, ones.shape

(2, torch.Size([3, 4]))

# Creating a range of tensors and tensors-like

In [224]:
torch.arange(60, 70)

tensor([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [225]:
try_range = torch.arange(start = 1, end = 16, step = 2) # simmilar to numpy arange
try_range

tensor([ 1,  3,  5,  7,  9, 11, 13, 15])

In [226]:
# Creating tensors like
ten_zeros = torch.zeros_like(input = try_range) # it will give zeroes in simmilar shape to try_range, like method helps withthe same
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Datatypes
*  *NOTE* : tensor datatypes is one of the 3 big errors we run into with Pytorch , in ML and DL

1.   Tensors not right datatype
2.   Tensors not right shape
3.   Tensors not on the right device


* perecision : How many bits we use to represent a number → determines how accurate it is and how much error creeps in.
* more precision = more bits 16 -> 32 -> 64





In [227]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # what datatype
                               device = "cpu", # what device is your tensor on
                               requires_grad = False) # wether or not to tracck gradient with this tensor operation
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [228]:
float_16_tensor = float_32_tensor.type(torch.float16)

float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [229]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [230]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [231]:
tensor01 = torch.rand(3,4)
tensor01

tensor([[0.0755, 0.4751, 0.6986, 0.3231],
        [0.8426, 0.8993, 0.6102, 0.3227],
        [0.0203, 0.4270, 0.8591, 0.0966]])

In [232]:
tensor01.shape

torch.Size([3, 4])

In [233]:
tensor01.size()

torch.Size([3, 4])

In [234]:
tensor01.device

device(type='cpu')

In [235]:
tensor01.dtype

torch.float32

# Manupulating tensors
 #### Tensor operations

 [Matrix Multiplication Visualization](https://www.matrixmultiplication.xyz)

In [236]:
tensor = torch.tensor([10, 42, 19])
tensor

tensor([10, 42, 19])

In [237]:
# add 10 to tensor
tensor  = tensor + 10
tensor

tensor([20, 52, 29])

In [238]:
# substract 10
tensor = tensor - 10
tensor

tensor([10, 42, 19])

In [239]:
torch.mul(tensor, 10)

tensor([100, 420, 190])

In [240]:
torch.add(tensor, 10)

tensor([20, 52, 29])

### Matrix Multiplication

1.   Element wise mulatiplication
2.   Matrix multiplication



In [241]:
tensor

tensor([10, 42, 19])

In [242]:
tensor * tensor

tensor([ 100, 1764,  361])

In [243]:
torch.matmul(tensor, tensor) # or @ for matrix multiplication or torch.mm(t1, t2)

tensor(2225)

In [244]:
tensor_1 = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6]
]) # (3 X 2)
tensor_2 = torch.tensor([
    [5, 9],
    [7, 1],
    [4, 2]
]) # (3 X 2)

In [245]:
tensor_1 @ tensor_2

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [246]:
tensor_2 = tensor_2.T # or tensor_2.reshape(2, 3)
tensor_2

tensor([[5, 7, 4],
        [9, 1, 2]])

In [247]:
tensor_1 @ tensor_2, (tensor_1 @ tensor_2).shape # or tennsor.matmul(tensor_1, tensor_2)

(tensor([[23,  9,  8],
         [51, 25, 20],
         [79, 41, 32]]),
 torch.Size([3, 3]))

### Aggreagated Functions

In [248]:
x = torch.arange(0, 200, 20)
x

tensor([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180])

In [249]:
torch.min(x) , x.min()

(tensor(0), tensor(0))

In [250]:
torch.max(x)

tensor(180)

In [251]:
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [252]:
x = x.type(torch.float32)

In [253]:
x.mean(), torch.mean(x)

(tensor(90.), tensor(90.))

In [254]:
x.sum()

tensor(900.)

In [255]:
x.median()

tensor(80.)

In [256]:
torch.mode(x)

torch.return_types.mode(
values=tensor(0.),
indices=tensor(0))

### Postional min,max - gives the inedex postion of min, max occuring value

In [257]:
x.argmin()

tensor(0)

In [258]:
x.argmax()

tensor(9)

 ### Reshaping, stacking, squeezing and unsqueezing tensors

*   Reshaping : reshape an input tensor to a defined shape
*   View : Retain a view of an input tensor of certain shape without changing the orginal tensor in the memory
* Stacking : combinne multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze : removes all `1` dimentions from a tensor
* unsqueeze : add a `1` dimention to a targer tensor
* Permute : Return a view of the input with dimentions permuted (swapped) in a certain way


In [259]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [260]:
x_reshaped = x.reshape(1,9)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [261]:
x_reshaped.shape

torch.Size([1, 9])

In [262]:
# Change the view
z = x.view(3, 3)
z

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [263]:
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [264]:
# Stacking tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [265]:
# toch.squeeze() - removes all the single dimentions from a target tensor
print(f"Previous tensor : {x_reshaped}")
print(f"Previous shape : {x_reshaped.shape}")

# Remove extra dimentions
x_squeezed = x_reshaped.squeeze()
print(f"New tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor : tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape : torch.Size([1, 9])
New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [266]:
# Squeeeeeeeeeeeeeze
x = torch.zeros(2, 1, 2, 1, 2)
x, x.size()



(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [267]:
x_reshaped.shape, x_reshaped.squeeze()

(torch.Size([1, 9]), tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [268]:
x_reshaped.squeeze().shape

torch.Size([9])

In [269]:
x_squeezed= x.squeeze()
x_squeezed

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [270]:
x_squeezed.shape

torch.Size([2, 2, 2])

In [271]:
# torch.unsqueeze() : adds a single dimention to a target tensor at a speceficc dim
print(f"Previous target : {x_squeezed}")
print(f"Previous shape : {x_squeezed.shape}")

# Add an extra dimention with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1) # dim = index where you want to add dimention ex [2, 1, 2, 2] at 1th intex
print(f"New tensor : {x_unsqueezed}")
print(f"New shape : {x_unsqueezed.shape}")

Previous target : tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
Previous shape : torch.Size([2, 2, 2])
New tensor : tensor([[[[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]]]])
New shape : torch.Size([2, 1, 2, 2])


In [272]:
# Permute
# torch.permute - rearrange the dimentions of a target in a specefied order or swap the dimention's
x_og = torch.rand(224, 224, 3) # [height, width, color channels ~ red, green and blue]
x_og.shape

torch.Size([224, 224, 3])

In [273]:
# Permute the original tensor tp rearrange the axis (or dim) order
x_og[0, 0, 0] = 25
x_permuted  = x_og.permute(2, 0 , 1) # swapped 0 -> 2, 1 -> 0, 2 -> 1
print(f"Previous Shape : {x_og.shape}")
print(f"New shape : {x_permuted.shape}")

Previous Shape : torch.Size([224, 224, 3])
New shape : torch.Size([3, 224, 224])


In [274]:
x_og[0, 0, 0],x_permuted[0, 0, 0]

(tensor(25.), tensor(25.))

# Indexing (Seleecting data from tensors)
#### similer to numpy
`[2D][1D][0D] [2d[1d[0d]]]`

In [349]:
torch.manual_seed(42)
x = torch.randint(0, 10, (3,3,3))
x, x.shape


(tensor([[[2, 7, 6],
          [4, 6, 5],
          [0, 4, 0]],
 
         [[3, 8, 4],
          [0, 4, 1],
          [2, 5, 5]],
 
         [[7, 6, 9],
          [6, 3, 1],
          [9, 3, 1]]]),
 torch.Size([3, 3, 3]))

In [350]:
x[0, 0]

tensor([2, 7, 6])

In [351]:
x[2][2][2] # [2D][1D][0D]

tensor(1)

In [352]:
# ":" can be used to sellect call of a target dimention
x[:,0]

tensor([[2, 7, 6],
        [3, 8, 4],
        [7, 6, 9]])

In [353]:
# Get all values of 0th and 1st dimentions but only index 1 and 2nd dimentions
x[:, :, 1]

tensor([[7, 6, 4],
        [8, 4, 5],
        [6, 3, 3]])

In [354]:
# Get all values of 0th and 1st dimentions but only 1 index value of 1st and 2nd dimentions
x[:, 1, 1]

tensor([6, 4, 3])

In [355]:
# Get index 0 of 0th and 1st ddimention and all values of 2nd dimention
x[0,0,:]

tensor([2, 7, 6])

# Pytorch Tensor and Numpy
to interact with numpy wee use
*   Data in NumPy, want in PyTorch tensor -> torch.from_numpy(ndarray)
*   PyTorch tensor -> NumPy -> torch.Tensor.numpy()




In [368]:
# NumPy to Torch
import torch
import numpy as np
z = np.arange(0., 11.)
z

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [371]:
x = torch.from_numpy(z)
z, x # torch's default data type when creating a float is float32, but know that here it create's a float64 tensor

(array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        dtype=torch.float64))

In [372]:
y = torch.Tensor.numpy(x)
x,y

(tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        dtype=torch.float64),
 array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))